### ISSUE TITLE
Ähnlichkeitsmaß für Graphen definieren

### ISSUE THREAD

**Issue by roman-at-github** [felixlinker/gbn1920_chrifero#2]

**Comment by roman-at-github** [comment]
- heuristisch mit anteil möglicher Kanten im Modularprodukt
- all-vs-all distanzmaß

**Comment by felixlinker** [comment]
Ich befürchte, die Idee mit diesem konkreten heuristischen Ansatz funktioniert (so) nicht.

Im Wikipedia Artikel zum modularen Produkt ist ein Beispiel vom Produkt zweier isomorpher Graphen:
https://en.wikipedia.org/wiki/Modular_product_of_graphs

Dort kann man sehen, dass das modulare Produkt dann nicht vollständig ist. Wäre der Graph vollständig, würde das bedeuten, dass jede Abbildung zwischen den Knoten der Graphen ein Isomorphismus ist. Das ist allerdings vollkommen irrelevant. Ob es nun einen Isomorphismus oder sehr, sehr viele gibt, sagt nichts über die Ähnlichkeit der Graphen, sondern deren Komplexität aus.

Vielleicht klappt es ja doch, aber ich kann mir sehr gut vorstellen, dass wir nach einer anderen Heuristik suchen sollten.
